name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "lib/httpsensible/version.rb"

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_gem_release.yml@main
    secrets:
      rubygems_api_key: ${{ secrets.SISYPHUS_RUBYGEMS_API_KEY }}
      gh_token: ${{ secrets.SISYPHUS_PUSH_TO_PROTECTED_BRANCH }}
    with:
      gem_name: httpsensible
      version_filepath: lib/httpsensible/version.rb
