name: Sorbet

on:
  pull_request_target:
    paths:
      - "**/*.rb"
      - "Gemfile.lock"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_SISYPHUS_YETTO_REPO_TOKEN }}

      - uses: yettoapp/actions/run-sorbet-update@main
