name: Test

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_test_suite.yml@main
    secrets:
      gh_token: ${{ secrets.GH_SISYPHUS_YETTO_REPO_TOKEN }}
